#!/usr/bin/env python3
# Copyright 2026 QuantumBridge Contributors.
# Licensed under the Apache License, Version 2.0.
# This file is independently implemented for QuantumBridge SDK.
# No source code from Qiskit or PennyLane was copied.
# Design source: docs/roadmap/p2_upstream_integration_strategy_v0.1.md.

from __future__ import annotations

import importlib
import inspect
from pathlib import Path


MODULES = [
    "qiskit_nature.second_q.drivers",
    "qiskit_nature.second_q.operators",
    "qiskit_nature.second_q.hamiltonians",
    "qiskit_nature.second_q.mappers",
    "qiskit_nature.second_q.problems",
    "qiskit_nature.second_q.properties",
    "qiskit_nature.second_q.transformers",
    "qiskit_nature.second_q.circuit.library",
    "qiskit_nature.second_q.algorithms",
    "qiskit_nature.second_q.formats",
    "qiskit_nature.second_q.hamiltonians.lattices",
    "qiskit_nature.utils",
]


def classify(name: str) -> tuple[str, str]:
    lowered = name.lower()
    if "driver" in lowered:
        return "Adapter", "optional qiskit-nature"
    if any(part in lowered for part in ("mapper", "operator", "hamiltonian")):
        return "Adapter", "optional qiskit-nature"
    if any(part in lowered for part in ("solver", "algorithm", "groundstate")):
        return "Upstream Passthrough", "optional qiskit-nature"
    return "Planned", "optional qiskit-nature"


def inventory():
    rows = []
    unavailable = []
    for module_name in MODULES:
        try:
            module = importlib.import_module(module_name)
        except Exception as exc:
            unavailable.append((module_name, type(exc).__name__))
            continue
        for name, value in inspect.getmembers(module):
            if name.startswith("_"):
                continue
            if inspect.isclass(value) or inspect.isfunction(value):
                mode, dependency = classify(name)
                kind = "class" if inspect.isclass(value) else "function"
                rows.append((f"{module_name}.{name}", kind, "Inventory only", mode, dependency, "planned", "medium", "runtime introspection only"))
    return rows, unavailable


def write_markdown(rows, unavailable):
    out_dir = Path("docs/compat")
    out_dir.mkdir(parents=True, exist_ok=True)
    header = "| Upstream API | Type | QuantumBridge Status | Mode | Dependency | Test | Risk | Notes |\n|---|---|---|---|---|---|---|---|\n"
    body = "".join(f"| `{api}` | {kind} | {status} | {mode} | {dep} | {test} | {risk} | {notes} |\n" for api, kind, status, mode, dep, test, risk, notes in rows)
    if not rows:
        body = "| `qiskit_nature` | package | unavailable | Planned | optional qiskit-nature | skipped | medium | optional dependency not installed during inventory generation |\n"
    note = "\n## Unavailable modules\n\n" + "\n".join(f"- `{name}`: `{reason}`" for name, reason in unavailable) + "\n" if unavailable else ""
    content = "# Qiskit Nature Public API Inventory\n\nGenerated by QuantumBridge runtime introspection. No upstream source or documentation text is copied.\n\n" + header + body + note
    Path("docs/compat/qiskit_nature_public_api_inventory.md").write_text(content)
    Path("docs/compat/qiskit_nature_feature_parity_matrix.md").write_text(content.replace("Public API Inventory", "Feature Parity Matrix"))


if __name__ == "__main__":
    write_markdown(*inventory())
