# Copyright 2026 QuantumBridge Contributors.
# Licensed under the Apache License, Version 2.0.
# This file is independently implemented for QuantumBridge SDK.
# No source code from Qiskit or PennyLane was copied.
# Design source: docs/roadmap/p2_execution_plan_v0.1.md.

# --- P2 Result Schema (Stage 6) ---
from .errors import SchemaValidationError
from .result_schema import RESULT_SCHEMA_VERSION, make_result_payload
from .serialization import from_json, to_json
from .validation import validate_result_schema

# --- Stage 7 Ecosystem Schemas (optional, may require extra dependencies) ---
try:
    from quantumbridge.schema.ecosystem_results import (
        AerResult,
        AlgorithmsResult,
        ChemistryResult,
        DynamicsResult,
        EcosystemResult,
        ExperimentsResult,
        FinanceResult,
        MLResult,
        MetalDesignResult,
        OptimizationResult,
    )
    from quantumbridge.schema.pennylane_results import (
        ConversionResult,
        DeviceResult,
        GradientResult,
        MeasurementResult,
        MeasurementBridgeResult,
        OperationBridgeResult,
        PennyLaneResult,
        QChemResult,
        QCutResult,
        QNNResult,
        QNodeResult,
        QOSUQCIJobSpecResult,
        QiskitBridgeResult,
        ResourceResult,
        ShadowResult,
        TapeBridgeResult,
        TemplateResult,
        TransformResult,
    )
    from quantumbridge.schema.qiskit_results import (
        AddonsAdvisoryResult,
        AerResult as QiskitAerResult,
        AlgorithmsResult as QiskitAlgorithmsResult,
        DynamicsResult as QiskitDynamicsResult,
        ExperimentsResult as QiskitExperimentsResult,
        FinanceResult as QiskitFinanceResult,
        MachineLearningResult,
        MetalAdvisoryResult,
        NatureResult,
        OptimizationResult as QiskitOptimizationResult,
        QiskitConversionResult,
        QiskitCoreResult,
        QiskitResult,
        RuntimeOfflineResult,
    )
    from quantumbridge.schema.optimization_results import (
        BruteForceOptimizationResult,
        IsingConversionResult,
        OptimizationComparisonResult,
        OptimizationResult as NativeOptimizationSchemaResult,
        QuadraticProgramResult,
        QUBOConversionResult,
        UpstreamOptimizationResult,
    )
    from quantumbridge.schema.algorithms_results import (
        AlgorithmComparisonResult,
        AlgorithmsResult as NativeAlgorithmsSchemaResult,
        EigensolverResult,
        GroverResult,
        NativeAlgorithmResult,
        QAOAResult,
        UpstreamAlgorithmResult,
        VQEResult,
    )
    from quantumbridge.schema.chemistry_results import (
        ChemistryComparisonResult,
        ChemistryResult as NativeChemistrySchemaResult,
        ExactDiagonalizationResult,
        H2WorkflowResult,
        LiHWorkflowResult,
        MolecularProblemResult,
        QubitHamiltonianResult,
        UpstreamNatureResult,
    )
    from quantumbridge.schema.ml_results import (
        KernelClassifierResult,
        MachineLearningResult as NativeMachineLearningSchemaResult,
        MLComparisonResult,
        QNNClassifierResult,
        QNNForwardResult,
        QuantumKernelResult,
        UpstreamMLResult,
    )
    __all__ = [
        # P2 schema exports
        "RESULT_SCHEMA_VERSION",
        "SchemaValidationError",
        "from_json",
        "make_result_payload",
        "to_json",
        "validate_result_schema",
        # Stage 7 ecosystem exports (optional, may require extras)
        "AerResult",
        "AlgorithmsResult",
        "ChemistryResult",
        "DynamicsResult",
        "EcosystemResult",
        "ExperimentsResult",
        "FinanceResult",
        "MLResult",
        "MetalDesignResult",
        "OptimizationResult",
        "PennyLaneResult",
        "ConversionResult",
        "DeviceResult",
        "GradientResult",
        "MeasurementResult",
        "MeasurementBridgeResult",
        "OperationBridgeResult",
        "QChemResult",
        "QCutResult",
        "QNNResult",
        "QNodeResult",
        "QOSUQCIJobSpecResult",
        "QiskitBridgeResult",
        "ResourceResult",
        "ShadowResult",
        "TapeBridgeResult",
        "TemplateResult",
        "TransformResult",
        "AddonsAdvisoryResult",
        "MachineLearningResult",
        "MetalAdvisoryResult",
        "NatureResult",
        "QiskitAerResult",
        "QiskitAlgorithmsResult",
        "QiskitConversionResult",
        "QiskitCoreResult",
        "QiskitDynamicsResult",
        "QiskitExperimentsResult",
        "QiskitFinanceResult",
        "QiskitOptimizationResult",
        "QiskitResult",
        "RuntimeOfflineResult",
        "BruteForceOptimizationResult",
        "IsingConversionResult",
        "NativeOptimizationSchemaResult",
        "OptimizationComparisonResult",
        "QuadraticProgramResult",
        "QUBOConversionResult",
        "UpstreamOptimizationResult",
        "AlgorithmComparisonResult",
        "ChemistryComparisonResult",
        "EigensolverResult",
        "ExactDiagonalizationResult",
        "GroverResult",
        "H2WorkflowResult",
        "LiHWorkflowResult",
        "MolecularProblemResult",
        "NativeAlgorithmResult",
        "NativeAlgorithmsSchemaResult",
        "NativeChemistrySchemaResult",
        "QAOAResult",
        "QubitHamiltonianResult",
        "UpstreamAlgorithmResult",
        "UpstreamNatureResult",
        "VQEResult",
        "KernelClassifierResult",
        "MLComparisonResult",
        "NativeMachineLearningSchemaResult",
        "QNNClassifierResult",
        "QNNForwardResult",
        "QuantumKernelResult",
        "UpstreamMLResult",
    ]
except ImportError:
    # Fallback when ecosystem extras not installed
    __all__ = [
        "RESULT_SCHEMA_VERSION",
        "SchemaValidationError",
        "from_json",
        "make_result_payload",
        "to_json",
        "validate_result_schema",
    ]
